#FileExistsError
fp=open("abc.txt",'x')
fp.read()

#FileExistsError: [Errno 17] File exists: 'abc.txt'